// <auto-generated />
using System;
using Gma.Modules.TaskRuntime.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gma.Modules.TaskRuntime.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(TaskRuntimeDbContext))]
    [Migration("20260804062445_AddTaskRuntimeScopeLifecycle")]
    partial class AddTaskRuntimeScopeLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tasks")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gma.Framework.Tasks.Infrastructure.TaskControlMessageState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EnqueuedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScopeId", "Id");

                    b.HasIndex("Status", "CompletedAtUtc");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.HasIndex("RunId", "Status", "EnqueuedAtUtc");

                    b.ToTable("task_control_messages", "tasks");
                });

            modelBuilder.Entity("Gma.Framework.Tasks.Infrastructure.TaskRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveDeduplicationIdentity")
                        .HasMaxLength(768)
                        .HasColumnType("character varying(768)");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancellationRequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaseGeneration")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LeasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NodeId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .HasColumnType("character varying(262144)");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ScheduledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkerGroup")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveDeduplicationIdentity")
                        .IsUnique();

                    b.HasIndex("ModuleName", "TaskName");

                    b.HasIndex("ScopeId", "CreatedAtUtc");

                    b.HasIndex("Status", "CompletedAtUtc");

                    b.HasIndex("WorkerGroup", "ScheduledAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("ModuleName", "TaskName", "ScopeId", "DeduplicationKey", "Status");

                    b.HasIndex("WorkerGroup", "Status", "ScheduledAtUtc", "NextAttemptAtUtc", "LockedUntilUtc");

                    b.ToTable("task_runs", "tasks");
                });

            modelBuilder.Entity("Gma.Modules.TaskRuntime.Persistence.Entities.TaskRuntimeScopeDestroyOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("ProofVersion")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("task_scope_destroy_operations", "tasks", t =>
                        {
                            t.HasCheckConstraint("CK_task_scope_destroy_operations_batch", "\"BatchSize\" >= 1 AND \"BatchSize\" <= 1000");

                            t.HasCheckConstraint("CK_task_scope_destroy_operations_counts", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0");

                            t.HasCheckConstraint("CK_task_scope_destroy_operations_revision", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_task_scope_destroy_operations_stage", "\"Stage\" >= 1 AND \"Stage\" <= 4");
                        });
                });

            modelBuilder.Entity("Gma.Modules.TaskRuntime.Persistence.Entities.TaskRuntimeScopeDestroyReceipt", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatchSize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("integer");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<int>("RemovalProofVersion")
                        .HasColumnType("integer");

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeId")
                        .IsUnique();

                    b.ToTable("task_scope_destroy_receipts", "tasks", t =>
                        {
                            t.HasCheckConstraint("CK_task_scope_destroy_receipts_batch", "\"BatchSize\" >= 1 AND \"BatchSize\" <= 1000");

                            t.HasCheckConstraint("CK_task_scope_destroy_receipts_counts", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0");

                            t.HasCheckConstraint("CK_task_scope_destroy_receipts_revision", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");
                        });
                });

            modelBuilder.Entity("Gma.Modules.TaskRuntime.Persistence.Entities.TaskRuntimeScopeState", b =>
                {
                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("SelectedRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScopeId");

                    b.HasIndex("OperationId")
                        .IsUnique();

                    b.HasIndex("Status", "ScopeId");

                    b.ToTable("task_scope_states", "tasks", t =>
                        {
                            t.HasCheckConstraint("CK_task_scope_states_revision", "\"SelectedRevision\" >= 0 AND \"ResultingRevision\" = \"SelectedRevision\" + 1");

                            t.HasCheckConstraint("CK_task_scope_states_status", "\"Status\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Gma.Framework.Tasks.Infrastructure.TaskControlMessageState", b =>
                {
                    b.HasOne("Gma.Framework.Tasks.Infrastructure.TaskRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
